### ISSUE TITLE
Support Serverless 3.0

### ISSUE THREAD

**Issue by fredrik** [neovasili/serverless-cloudfront-api-route#12]
The plugin currently only supports Serverless 2.x. Would it be possible to add support for the latest Serverless 3.0? I'd love to help out if needed!

Edit: based on my limited testing, the plugin works just fine with Serverless v3! Just need to bump the serverless peer dep.

**Comment by fredrik** [comment]
@neovasili, what do you think of releasing a new version of serverless-cloudfront-api-route with support for Serverless 3?

**Comment by neovasili** [comment]
Hi @fredrik,

Will take a look when I can, definitely a worthy change, but unfortunately my capacity is quite limited lately.

Any contribution is obviously welcome 😄
